### ISSUE TITLE
decryptAES should be implemented

### ISSUE THREAD

**Issue by mimopotato** [mimopotato/funcml-ruby#10]
```yaml
key:
  _decryptAES:
    data: encrypted-string
    encryption_key: string
```
