### ISSUE TITLE
keys should be implemented

### ISSUE THREAD

**Issue by mimopotato** [mimopotato/funcml-ruby#14]
_keys should only returns keys from a hash as array.

```yaml
hashes: {key: value, second-key: value}

all_keys:
  _keys: $hashes
```
Would be rendered as:

```yaml
all_keys:
  - key
  - second-key
```
