### ISSUE TITLE
values should be implemented

### ISSUE THREAD

**Issue by mimopotato** [mimopotato/funcml-ruby#15]
_values should only returns values from a hash as array.

```yaml
hashes: {key: value, second-key: second-value}

all_values:
  _values: $hashes
```

Would be rendered as:

```yaml
all_values:
  - value
  - second-value
```
