### ISSUE TITLE
first should be implemented

### ISSUE THREAD

**Issue by mimopotato** [mimopotato/funcml-ruby#16]
```yaml
keys: [1, 2, 3]

key:
  _first: $keys
```

```yaml
key: 1
```
