### ISSUE TITLE
tail should be implemented

### ISSUE THREAD

**Issue by mimopotato** [mimopotato/funcml-ruby#17]
```yaml
keys: [1, 2, 3]

key:
  _tail: [$keys, 2]
```

```yaml
key:
  - 2
  - 3
```
