### ISSUE TITLE
head should be implemented

### ISSUE THREAD

**Issue by mimopotato** [mimopotato/funcml-ruby#18]
```yaml
keys: [1, 2, 3]

key:
  _head: [$keys, 2]
```

```yaml
key:
  - 1
  - 2
```
