### ISSUE TITLE
reverse should be implemented

### ISSUE THREAD

**Issue by mimopotato** [mimopotato/funcml-ruby#19]
```yaml
keys: [1, 2, 3]

result:
  _reverse: $keys
```

```yaml
result:
  - 3
  - 2
  - 1
```
