### ISSUE TITLE
uniq should be implemented

### ISSUE THREAD

**Issue by mimopotato** [mimopotato/funcml-ruby#20]
```yaml

keys: [1, 1, 2, 3]

result:
  _uniq: $keys
```

```yaml
result:
  - 1
  - 2
  - 3
```
