### ISSUE TITLE
index should be implemented

### ISSUE THREAD

**Issue by mimopotato** [mimopotato/funcml-ruby#21]
```yaml

keys: ["first", "second", "last"]

result:
  _index: [$keys, "first"]
```

```yaml
result: 0
```
