### ISSUE TITLE
until should be implemented

### ISSUE THREAD

**Issue by mimopotato** [mimopotato/funcml-ruby#22]
until should always return an array of block value.
```yaml
result:
  _until: 5
  value: $item
```

```yaml
result:
  - value: 0
  - value: 1
  - value: 2
  - value: 3
  - value: 4
```
