### ISSUE TITLE
b64decode should be implemented

### ISSUE THREAD

**Issue by mimopotato** [mimopotato/funcml-ruby#3]
Using the included Ruby base64 library.

```yaml
key:
  _b64decode: |
    aGVsbG8=
```
