### ISSUE TITLE
encryptAES should be implemented

### ISSUE THREAD

**Issue by mimopotato** [mimopotato/funcml-ruby#9]
Encryption using AES should be implemented. Using a mutated encryption key, loaded from string or variable, a data field should be return with encrypted string.

```yaml
key:
  _encryptAES:
    data: string
    encryptionKey: string 
```
